version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/clinicpro_prod
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-vlW68dorN32H88cYR7HQf0uM0ptg2x8IJeXkSXL8R5HNm6pvD4oGazWkOuIv4d7R}
      PHX_HOST: ${PHX_HOST:-localhost}
      POOL_SIZE: ${POOL_SIZE:-10}
      SEED_DATABASE: ${SEED_DATABASE:-true}
      # M-Pesa placeholders
      MPESA_DEFAULT_CONSUMER_KEY: ${MPESA_DEFAULT_CONSUMER_KEY:-placeholder_key}
      MPESA_DEFAULT_CONSUMER_SECRET: ${MPESA_DEFAULT_CONSUMER_SECRET:-placeholder_secret}
      MPESA_DEFAULT_PASSKEY: ${MPESA_DEFAULT_PASSKEY:-placeholder_passkey}
      MPESA_DEFAULT_SHORTCODE: ${MPESA_DEFAULT_SHORTCODE:-placeholder_shortcode}
      # Paystack placeholders
      PAYSTACK_PUBLIC_KEY: ${PAYSTACK_PUBLIC_KEY:-placeholder_public_key}
      PAYSTACK_SECRET_KEY: ${PAYSTACK_SECRET_KEY:-placeholder_secret_key}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicpro_prod
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
