#!/bin/bash

echo "🚂 Railway Project Token Setup for CI/CD"
echo "======================================="
echo ""
echo "To set up automated deployment, you need to create a Railway API token:"
echo ""
echo "1. Go to Railway Dashboard: https://railway.app/account/tokens"
echo "2. Click 'Create Token'"
echo "3. Select 'Project Token' (NOT Account Token)"
echo "4. Select the ClinicPro project"
echo "5. Give it a name like 'GitHub Actions CI/CD'"
echo "6. Copy the generated token"
echo ""
echo "Then run this command to set the GitHub secret:"
echo "gh secret set RAILWAY_TOKEN --body \"your_token_here\""
echo ""
echo "Alternative: If you have the token ready, you can run:"
echo "read -s -p \"Enter Railway Token: \" RAILWAY_TOKEN"
echo "gh secret set RAILWAY_TOKEN --body \"\$RAILWAY_TOKEN\""
echo ""
echo "After setting the token, push your changes to trigger the CI/CD pipeline:"
echo "git add ."
echo "git commit -m \"Update CI/CD pipeline for Railway deployment\""
echo "git push origin main"
echo ""
echo "📋 Current GitHub Secrets:"
gh secret list 2>/dev/null || echo "Run 'gh auth login' first if you see an error above"
