name: Deploy ClinicPro to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clinicpro_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.2'
        otp-version: '26'
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Install dependencies
      run: mix deps.get
      
    - name: Check formatting
      run: mix format --check-formatted
      
    - name: Compile application
      run: mix compile
      env:
        MIX_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/clinicpro_test
        
    - name: Setup database
      run: mix ecto.setup
      env:
        MIX_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/clinicpro_test
      continue-on-error: true
        
    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/clinicpro_test
      continue-on-error: true

  build-and-deploy:
    needs: test
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/cleanup/mpesa-removal')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        railway --version
    
    - name: Set Railway environment variables
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        echo "Setting Railway environment variables..."
        SECRET_KEY_BASE=$(openssl rand -base64 64 | tr -d '\n')
        railway link --environment production --project desirable-integrity --service clinicpro-ash
        railway variables --set "SECRET_KEY_BASE=$SECRET_KEY_BASE"
        railway variables --set "DATABASE_URL=ecto://postgres:XkggcTaQwXrloywONDieBlwLeGSGEhDS@postgres-p8mu.railway.internal:5432/railway"
        railway variables --set "PHX_SERVER=true"
        railway variables --set "PHX_HOST=clinicpro-ash-production.up.railway.app"
        railway variables --set "PORT=4000"
        railway variables --set "ECTO_IPV6=true"
        railway variables --set "LANG=en_US.UTF-8"
        railway variables --set "LC_CTYPE=en_US.UTF-8"
    
    - name: Deploy to Railway
      run: |
        echo "Deploying to Railway..."
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        # Wait for deployment to complete
        sleep 30
        
        # Run verification script
        chmod +x ./verify_deployment.sh
        ./verify_deployment.sh https://clinicpro-ash-production.up.railway.app || true
